services:
  - type: web
    name: frontend-solution
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
    healthCheckPath: /
